Repository kookmin-sw/capstone-2022-17, pull requests merged in 2022-05, with the labels that each got.

#16 feat: common primary btn
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/common/PrimaryBtn.jsx
  frontend/yarn.lock
Labels: 👀 In review

#14 feat: logo component
  frontend/src/components/Nav/Logo.jsx
  frontend/src/styles/theme.js
Labels: 👀 In review

#17 feat: Notificatation Icon component
  frontend/src/components/Nav/NotiIcon.jsx
Labels: 👏 Merge Needed

#15 feat: NavMenu component
  frontend/src/components/Nav/NavMenu.jsx
Labels: 👀 In review

#9 feature: Card/CardStatus
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Card/CardStatus.js
  frontend/src/styles/theme.js
  frontend/yarn.lock
Labels: 👏 Merge Needed

#7 feature/Card_CardName
  frontend/src/components/Card/CardName.js
Labels: 👏 Merge Needed

#18 feat: UserMenu components
  frontend/package.json
  frontend/src/components/Nav/UserMenu/Avatar.jsx
  frontend/src/components/Nav/UserMenu/UserMenu.jsx
  frontend/yarn.lock
Labels: 👀 In review

#13 Front/feature/card card period
  frontend/src/components/Card/CardPeriod.js
  frontend/src/styles/theme.js
Labels: 👏 Merge Needed

#12 feature: Tag/Tag
  frontend/src/components/Tag/Tag.js
  frontend/src/styles/theme.js
Labels: 👏 Merge Needed

#11 feature: Card/CardHeadCount
  frontend/public/card/headCountImg.png
  frontend/src/components/Card/CardHeadCount.js
Labels: 👏 Merge Needed

#19 Front/feature/nav
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Nav/Logo.jsx
  frontend/src/components/Nav/Nav.jsx
  frontend/src/components/Nav/NavMenu.jsx
  frontend/src/components/Nav/NotiIcon.jsx
  frontend/src/components/Nav/SignBtn.jsx
  frontend/src/components/Nav/UserMenu/Avatar.jsx
  frontend/src/components/Nav/UserMenu/UserMenu.jsx
  frontend/src/layouts/responsive.layout.jsx
  frontend/src/pages/Home/Home.jsx
  frontend/src/styles/theme.js
  frontend/yarn.lock
Labels: 👏 Merge Needed

#20 feature: 좋아요
  frontend/src/components/Likes.jsx
Labels: 👀 In review

#23 back/feature/projectAPI
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/kookmin/capstone/backend/BackendApplication.java
  backend/src/main/java/kookmin/capstone/backend/InitDb.java
  backend/src/main/java/kookmin/capstone/backend/api/AmazonS3Controller.java
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/config/AwsS3Config.java
  backend/src/main/java/kookmin/capstone/backend/config/SecurityConfig.java
  backend/src/main/java/kookmin/capstone/backend/controller/SampleController.java
  backend/src/main/java/kookmin/capstone/backend/domain/DateEntity.java
  backend/src/main/java/kookmin/capstone/backend/domain/ExternalProjects.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/Project.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/UserRole.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/UserAuthDto.java
  backend/src/main/java/kookmin/capstone/backend/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/kookmin/capstone/backend/jwt/JwtTokenProvider.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/UserRepository.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/S3Uploader.java
  backend/src/main/java/kookmin/capstone/backend/service/auth/AuthService.java
  backend/src/main/java/kookmin/capstone/backend/service/auth/CustomUserDetailService.java
  backend/src/main/java/kookmin/capstone/backend/service/auth/UserDetailsImpl.java
  backend/src/main/resources/application.yml
  backend/src/test/java/kookmin/capstone/backend/repository/ProjectRepositoryTest.java
  backend/src/test/java/kookmin/capstone/backend/repository/UserRepositoryTest.java
  backend/src/test/java/kookmin/capstone/backend/repository/config/SecurityConfigTest.java
Labels: :bulb: Feature, 👏 Merge Needed

#28 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/AmazonS3Controller.java
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/Career.java
  backend/src/main/java/kookmin/capstone/backend/domain/Education.java
  backend/src/main/java/kookmin/capstone/backend/domain/ExternalProjects.java
  backend/src/main/java/kookmin/capstone/backend/domain/Oauth.java
  backend/src/main/java/kookmin/capstone/backend/domain/Portfolio.java
  backend/src/main/java/kookmin/capstone/backend/domain/Position.java
  backend/src/main/java/kookmin/capstone/backend/domain/ProjectTech.java
  backend/src/main/java/kookmin/capstone/backend/domain/Supervisor.java
  backend/src/main/java/kookmin/capstone/backend/domain/TechStack.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/PositionCnt.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/Project.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/ProjectPosition.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectSearchCond.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectTechRepository.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :earth_asia: Deploy

#33 back/feature/techAPI
  backend/src/main/java/kookmin/capstone/backend/api/TechStackApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/TechDTO.java
  backend/src/main/java/kookmin/capstone/backend/service/TechStackService.java
Labels: :earth_asia: Deploy

#36 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/Position.java
  backend/src/main/java/kookmin/capstone/backend/domain/PositionList.java
  backend/src/main/java/kookmin/capstone/backend/domain/ProjectTech.java
  backend/src/main/java/kookmin/capstone/backend/domain/member/Member.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/PositionCnt.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/Project.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/ProjectPosition.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/dto/MemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectPositionDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectSearchCond.java
  backend/src/main/java/kookmin/capstone/backend/dto/SimpleMemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/UserDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/MemberRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/PositionListRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/PositionRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/response/DefalutResponse.java
  backend/src/main/java/kookmin/capstone/backend/response/MemberResDTO.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/response/StatusCode.java
  backend/src/main/java/kookmin/capstone/backend/service/PositionService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#38 authAPI
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/authDTO/SignupDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/authDTO/response/ResponseDTO.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#40 authAPI
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/authDTO/SignupDTO.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#41 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/config/WebConfig.java
  backend/src/main/java/kookmin/capstone/backend/domain/Position.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/ProjectPosition.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/exception/authException/ExistNicknameException.java
  backend/src/main/java/kookmin/capstone/backend/exception/authException/ExistUserException.java
  backend/src/main/java/kookmin/capstone/backend/exception/authException/PasswordException.java
  backend/src/main/java/kookmin/capstone/backend/exception/memberException/MemberAddException.java
  backend/src/main/java/kookmin/capstone/backend/exception/memberException/MemberException.java
  backend/src/main/java/kookmin/capstone/backend/exception/projectException/DuplicateProjectException.java
  backend/src/main/java/kookmin/capstone/backend/exception/projectException/ProjectException.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepository.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy

#44 back/feature/auth
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/config/SecurityConfig.java
  backend/src/main/java/kookmin/capstone/backend/domain/member/Member.java
  backend/src/main/java/kookmin/capstone/backend/domain/member/MemberType.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/Project.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/MemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/MemberSignupRequestDto.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/RequestMemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/MemberRepository.java
  backend/src/main/java/kookmin/capstone/backend/response/MemberResDTO.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/UserService.java
  backend/src/main/java/kookmin/capstone/backend/service/jwt/CustomAuthenticationEntryPoint.java
  backend/src/main/java/kookmin/capstone/backend/service/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/kookmin/capstone/backend/service/jwt/JwtTokenService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#46 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/config/SecurityConfig.java
  backend/src/main/java/kookmin/capstone/backend/dto/ProjectPositionDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/MemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectPositionDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectSearchCond.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: 👏 Merge Needed

#47 back/feature/memberAPI
  backend/src/main/java/kookmin/capstone/backend/api/MemberAPiController.java
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/RequestMemberDTO.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#48 back/feature/memberAPI
  backend/src/main/java/kookmin/capstone/backend/api/MemberAPiController.java
  backend/src/main/java/kookmin/capstone/backend/config/SecurityConfig.java
  backend/src/main/java/kookmin/capstone/backend/domain/member/Member.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/ProjectPosition.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/DeleteMemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/RequestMemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/exception/memberException/DuplicateMemberException.java
  backend/src/main/java/kookmin/capstone/backend/repository/MemberRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/PositionRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/ProjectPositionRepository.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/PositionService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#51 back/feature/techAPI
  backend/src/main/java/kookmin/capstone/backend/api/TechStackApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/TechDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/TechStackDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/TechStackRepository.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/TechStackService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#53 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/MemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectRequestDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectResponseDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectTechDTO.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: 👏 Merge Needed

#56 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/Project.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectTechDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/customProjectRepository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#61 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/TechStackApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/Project.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/UserTech.java
  backend/src/main/java/kookmin/capstone/backend/dto/UserDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/RequestMemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectRequestDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserAuthDto.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserTechDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/UserTechRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/customProjectRepository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/UserService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#64 back/feature/userAPI
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
Labels: 👏 Merge Needed

#66 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectSearchCond.java
  backend/src/main/java/kookmin/capstone/backend/repository/customProjectRepository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#69 back/feature/memberAPI
  backend/src/main/java/kookmin/capstone/backend/api/MemberAPiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/memberDTO/RequestMemberDTO.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
Labels: :earth_asia: Deploy

#70 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectRequestDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/MemberRepository.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#72 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/MemberAPiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/Notification.java
  backend/src/main/java/kookmin/capstone/backend/domain/member/Member.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/dto/NotificationDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/MemberRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/NotificationRepositiory.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/NotificationSerivce.java
Labels: 👏 Merge Needed

#73 back/feature/portfolioAPI
  backend/src/main/java/kookmin/capstone/backend/api/PortfolioApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/Career.java
  backend/src/main/java/kookmin/capstone/backend/domain/Education.java
  backend/src/main/java/kookmin/capstone/backend/domain/ExternalProjects.java
  backend/src/main/java/kookmin/capstone/backend/domain/Portfolio.java
  backend/src/main/java/kookmin/capstone/backend/domain/portfolio/Career.java
  backend/src/main/java/kookmin/capstone/backend/domain/portfolio/Education.java
  backend/src/main/java/kookmin/capstone/backend/domain/portfolio/ExternalProject.java
  backend/src/main/java/kookmin/capstone/backend/domain/portfolio/ExternalProjectTech.java
  backend/src/main/java/kookmin/capstone/backend/domain/portfolio/Portfolio.java
  backend/src/main/java/kookmin/capstone/backend/domain/user/User.java
  backend/src/main/java/kookmin/capstone/backend/dto/portfolioDTO/CareerDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/portfolioDTO/EducationDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/portfolioDTO/ExternalProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/portfolioDTO/ExternalTechDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/portfolioDTO/PortfolioDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/PortfolioRepository.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/PortfolioService.java
Labels: 👏 Merge Needed

#76 back/feature/userAPI
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/UserService.java
Labels: :earth_asia: Deploy

#79 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectRequestDTO.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#82 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectRequestDTO.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#86 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/MyProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/member/Member.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserResDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/customProjectRepository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#87 back/feature/notifyAPI
  backend/src/main/java/kookmin/capstone/backend/api/MemberAPiController.java
  backend/src/main/java/kookmin/capstone/backend/api/MyProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/Notification.java
  backend/src/main/java/kookmin/capstone/backend/dto/NotificationDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/NotificationRepositiory.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#88 back/feature/fastAPI
  backend/build.gradle
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectDTO.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#91 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/authDTO/AuthRequestDTO.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserDTO.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#93 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
Labels: :bulb: Feature, :earth_asia: Deploy

#94 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/api/TempController.java
  backend/src/main/java/kookmin/capstone/backend/config/WebConfig.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#96 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/domain/project/ProjectPosition.java
  backend/src/main/java/kookmin/capstone/backend/dto/userDTO/UserResDTO.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#97 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/authDTO/AuthRequestDTO.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#98 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/api/AuthApiController.java
  backend/src/main/java/kookmin/capstone/backend/api/TempController.java
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/domain/project/ProjectPosition.java
  backend/src/main/java/kookmin/capstone/backend/repository/PositionRepository.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectPositionRepository.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiUserService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/UserService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#100 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectSearchCond.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#101 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/ProjectSearchCond.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
Labels: :earth_asia: Deploy, 👏 Merge Needed

#102 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/repository/customProjectRepository/ProjectRepositoryCustom.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepositoryImpl.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiUserService.java
  backend/src/main/java/kookmin/capstone/backend/service/MemberService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#103 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/api/TempController.java
  backend/src/main/java/kookmin/capstone/backend/repository/projectRepository/ProjectRepository.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiUserService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#104 back/feature/fastAPI
  backend/src/main/java/kookmin/capstone/backend/api/TempController.java
  backend/src/main/java/kookmin/capstone/backend/api/UserApiController.java
  backend/src/main/java/kookmin/capstone/backend/repository/UserRepository.java
  backend/src/main/java/kookmin/capstone/backend/response/ResponseMessage.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/FastApiUserService.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
  backend/src/main/java/kookmin/capstone/backend/service/UserService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed

#107 back/feature/projectAPI
  backend/src/main/java/kookmin/capstone/backend/api/ProjectApiController.java
  backend/src/main/java/kookmin/capstone/backend/dto/projectDTO/LikeDTO.java
  backend/src/main/java/kookmin/capstone/backend/exception/projectException/LikeException.java
  backend/src/main/java/kookmin/capstone/backend/service/ProjectService.java
Labels: :bulb: Feature, :earth_asia: Deploy, 👏 Merge Needed
